module.exports = {
  COMMENT_REPORT: 'COMMENT_REPORT',
  REPORT_MODAL: 'REPORT_MODAL',
  DISMISS_REPORT_MODAL: 'DISMISS_REPORT_MODAL',
  FILTER_MODAL: 'FILTER_MODAL',
  DISMISS_FILTER_MODAL: 'DISMISS_FILTER_MODAL',
  RESET_FILTER: 'RESET_FILTER',
  RECEIVE_RAW_REPORTS: 'RECEIVE_RAW_REPORTS',
  RECEIVE_RAW_FILTERS: 'RECEIVE_RAW_FILTERS',
};